version: "3.8"

services:
  moondream2:
    container_name: moondream2
    image: maximofn/moondream2:1.0.1
    build: .
    runtime: nvidia
    network_mode: "host"
    volumes:
      - ./hub:/root/.cache/huggingface/hub
      # - ./gradio_cached_examples:/moondream2/gradio_cached_examples
    tty: true
    stdin_open: true
